"use strict";
// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=none"
// @generated from file auth/auth.proto (package auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.LogoutResponse = exports.LogoutRequest = exports.RefreshTokenRequest = exports.ValidateTokenResponse = exports.ValidateTokenRequest = exports.AuthResponse = exports.SignInRequest = exports.SignUpRequest = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
const types_pb_1 = require("../common/types_pb");
/**
 * @generated from message auth.SignUpRequest
 */
class SignUpRequest extends protobuf_1.Message {
    /**
     * @generated from field: string email = 1;
     */
    email = "";
    /**
     * @generated from field: string password = 2;
     */
    password = "";
    /**
     * @generated from field: string display_name = 3;
     */
    displayName = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "auth.SignUpRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new SignUpRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SignUpRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SignUpRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SignUpRequest, a, b);
    }
}
exports.SignUpRequest = SignUpRequest;
/**
 * @generated from message auth.SignInRequest
 */
class SignInRequest extends protobuf_1.Message {
    /**
     * @generated from field: string email = 1;
     */
    email = "";
    /**
     * @generated from field: string password = 2;
     */
    password = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "auth.SignInRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "password", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new SignInRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new SignInRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new SignInRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(SignInRequest, a, b);
    }
}
exports.SignInRequest = SignInRequest;
/**
 * @generated from message auth.AuthResponse
 */
class AuthResponse extends protobuf_1.Message {
    /**
     * @generated from field: string access_token = 1;
     */
    accessToken = "";
    /**
     * @generated from field: string refresh_token = 2;
     */
    refreshToken = "";
    /**
     * @generated from field: common.UserInfo user = 3;
     */
    user;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "auth.AuthResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "user", kind: "message", T: types_pb_1.UserInfo },
    ]);
    static fromBinary(bytes, options) {
        return new AuthResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new AuthResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new AuthResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(AuthResponse, a, b);
    }
}
exports.AuthResponse = AuthResponse;
/**
 * @generated from message auth.ValidateTokenRequest
 */
class ValidateTokenRequest extends protobuf_1.Message {
    /**
     * @generated from field: string token = 1;
     */
    token = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "auth.ValidateTokenRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new ValidateTokenRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ValidateTokenRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ValidateTokenRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ValidateTokenRequest, a, b);
    }
}
exports.ValidateTokenRequest = ValidateTokenRequest;
/**
 * @generated from message auth.ValidateTokenResponse
 */
class ValidateTokenResponse extends protobuf_1.Message {
    /**
     * @generated from field: bool valid = 1;
     */
    valid = false;
    /**
     * @generated from field: string user_id = 2;
     */
    userId = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "auth.ValidateTokenResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "valid", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
        { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new ValidateTokenResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ValidateTokenResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ValidateTokenResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ValidateTokenResponse, a, b);
    }
}
exports.ValidateTokenResponse = ValidateTokenResponse;
/**
 * @generated from message auth.RefreshTokenRequest
 */
class RefreshTokenRequest extends protobuf_1.Message {
    /**
     * @generated from field: string refresh_token = 1;
     */
    refreshToken = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "auth.RefreshTokenRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new RefreshTokenRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RefreshTokenRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RefreshTokenRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(RefreshTokenRequest, a, b);
    }
}
exports.RefreshTokenRequest = RefreshTokenRequest;
/**
 * @generated from message auth.LogoutRequest
 */
class LogoutRequest extends protobuf_1.Message {
    /**
     * @generated from field: string refresh_token = 1;
     */
    refreshToken = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "auth.LogoutRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new LogoutRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new LogoutRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new LogoutRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(LogoutRequest, a, b);
    }
}
exports.LogoutRequest = LogoutRequest;
/**
 * @generated from message auth.LogoutResponse
 */
class LogoutResponse extends protobuf_1.Message {
    /**
     * @generated from field: bool success = 1;
     */
    success = false;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "auth.LogoutResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    ]);
    static fromBinary(bytes, options) {
        return new LogoutResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new LogoutResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new LogoutResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(LogoutResponse, a, b);
    }
}
exports.LogoutResponse = LogoutResponse;
//# sourceMappingURL=auth_pb.js.map