// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts,import_extension=none"
// @generated from file auth/auth.proto (package auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthResponse, LogoutRequest, LogoutResponse, RefreshTokenRequest, SignInRequest, SignUpRequest, ValidateTokenRequest, ValidateTokenResponse } from "./auth_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service auth.AuthService
 */
export const AuthService = {
  typeName: "auth.AuthService",
  methods: {
    /**
     * @generated from rpc auth.AuthService.SignUp
     */
    signUp: {
      name: "SignUp",
      I: SignUpRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.SignIn
     */
    signIn: {
      name: "SignIn",
      I: SignInRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.ValidateToken
     */
    validateToken: {
      name: "ValidateToken",
      I: ValidateTokenRequest,
      O: ValidateTokenResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.RefreshToken
     */
    refreshToken: {
      name: "RefreshToken",
      I: RefreshTokenRequest,
      O: AuthResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc auth.AuthService.Logout
     */
    logout: {
      name: "Logout",
      I: LogoutRequest,
      O: LogoutResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

