"use strict";
// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts,import_extension=none"
// @generated from file auth/auth.proto (package auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthService = void 0;
const auth_pb_1 = require("./auth_pb");
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from service auth.AuthService
 */
exports.AuthService = {
    typeName: "auth.AuthService",
    methods: {
        /**
         * @generated from rpc auth.AuthService.SignUp
         */
        signUp: {
            name: "SignUp",
            I: auth_pb_1.SignUpRequest,
            O: auth_pb_1.AuthResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc auth.AuthService.SignIn
         */
        signIn: {
            name: "SignIn",
            I: auth_pb_1.SignInRequest,
            O: auth_pb_1.AuthResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc auth.AuthService.ValidateToken
         */
        validateToken: {
            name: "ValidateToken",
            I: auth_pb_1.ValidateTokenRequest,
            O: auth_pb_1.ValidateTokenResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc auth.AuthService.RefreshToken
         */
        refreshToken: {
            name: "RefreshToken",
            I: auth_pb_1.RefreshTokenRequest,
            O: auth_pb_1.AuthResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc auth.AuthService.Logout
         */
        logout: {
            name: "Logout",
            I: auth_pb_1.LogoutRequest,
            O: auth_pb_1.LogoutResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
//# sourceMappingURL=auth_connect.js.map