// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts,import_extension=none"
// @generated from file blog/blog.proto (package blog, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreatePostRequest, CreatePostResponse, DeletePostRequest, DeletePostResponse, EditPostRequest, EditPostResponse, GetPostRequest, GetPostResponse, ListPostsRequest, ListPostsResponse, UploadUrlRequest, UploadUrlResponse } from "./blog_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service blog.PostService
 */
export const PostService = {
  typeName: "blog.PostService",
  methods: {
    /**
     * @generated from rpc blog.PostService.CreatePost
     */
    createPost: {
      name: "CreatePost",
      I: CreatePostRequest,
      O: CreatePostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc blog.PostService.GetPost
     */
    getPost: {
      name: "GetPost",
      I: GetPostRequest,
      O: GetPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc blog.PostService.ListPosts
     */
    listPosts: {
      name: "ListPosts",
      I: ListPostsRequest,
      O: ListPostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc blog.PostService.DeletePost
     */
    deletePost: {
      name: "DeletePost",
      I: DeletePostRequest,
      O: DeletePostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc blog.PostService.EditPost
     */
    editPost: {
      name: "EditPost",
      I: EditPostRequest,
      O: EditPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc blog.PostService.RequestUploadUrl
     */
    requestUploadUrl: {
      name: "RequestUploadUrl",
      I: UploadUrlRequest,
      O: UploadUrlResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

