"use strict";
// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=none"
// @generated from file blog/blog.proto (package blog, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.UploadUrlResponse = exports.UploadUrlRequest = exports.EditPostResponse = exports.EditPostRequest = exports.DeletePostResponse = exports.DeletePostRequest = exports.ListPostsResponse = exports.ListPostsRequest = exports.GetPostResponse = exports.GetPostRequest = exports.CreatePostResponse = exports.CreatePostRequest = exports.Category = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from enum blog.Category
 */
var Category;
(function (Category) {
    /**
     * @generated from enum value: UNSPECIFIED = 0;
     */
    Category[Category["UNSPECIFIED"] = 0] = "UNSPECIFIED";
    /**
     * @generated from enum value: TECHNOLOGY = 1;
     */
    Category[Category["TECHNOLOGY"] = 1] = "TECHNOLOGY";
    /**
     * @generated from enum value: DEVELOPMENT = 2;
     */
    Category[Category["DEVELOPMENT"] = 2] = "DEVELOPMENT";
    /**
     * @generated from enum value: DESIGN = 3;
     */
    Category[Category["DESIGN"] = 3] = "DESIGN";
    /**
     * @generated from enum value: LIFESTYLE = 4;
     */
    Category[Category["LIFESTYLE"] = 4] = "LIFESTYLE";
    /**
     * @generated from enum value: CAREER = 5;
     */
    Category[Category["CAREER"] = 5] = "CAREER";
})(Category || (exports.Category = Category = {}));
// Retrieve enum metadata with: proto3.getEnumType(Category)
protobuf_1.proto3.util.setEnumType(Category, "blog.Category", [
    { no: 0, name: "UNSPECIFIED" },
    { no: 1, name: "TECHNOLOGY" },
    { no: 2, name: "DEVELOPMENT" },
    { no: 3, name: "DESIGN" },
    { no: 4, name: "LIFESTYLE" },
    { no: 5, name: "CAREER" },
]);
/**
 * @generated from message blog.CreatePostRequest
 */
class CreatePostRequest extends protobuf_1.Message {
    /**
     * @generated from field: string author_id = 1;
     */
    authorId = "";
    /**
     * @generated from field: string title = 2;
     */
    title = "";
    /**
     * @generated from field: string content = 3;
     */
    content = "";
    /**
     * @generated from field: string image = 4;
     */
    image = "";
    /**
     * @generated from field: blog.Category category = 5;
     */
    category = Category.UNSPECIFIED;
    /**
     * @generated from field: int32 read_time = 6;
     */
    readTime = 0;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.CreatePostRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "author_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "category", kind: "enum", T: protobuf_1.proto3.getEnumType(Category) },
        { no: 6, name: "read_time", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    ]);
    static fromBinary(bytes, options) {
        return new CreatePostRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreatePostRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreatePostRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreatePostRequest, a, b);
    }
}
exports.CreatePostRequest = CreatePostRequest;
/**
 * @generated from message blog.CreatePostResponse
 */
class CreatePostResponse extends protobuf_1.Message {
    /**
     * @generated from field: string id = 1;
     */
    id = "";
    /**
     * @generated from field: google.protobuf.Timestamp created_at = 2;
     */
    createdAt;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.CreatePostResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "created_at", kind: "message", T: protobuf_1.Timestamp },
    ]);
    static fromBinary(bytes, options) {
        return new CreatePostResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CreatePostResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CreatePostResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(CreatePostResponse, a, b);
    }
}
exports.CreatePostResponse = CreatePostResponse;
/**
 * @generated from message blog.GetPostRequest
 */
class GetPostRequest extends protobuf_1.Message {
    /**
     * @generated from field: string id = 1;
     */
    id = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.GetPostRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new GetPostRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetPostRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetPostRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetPostRequest, a, b);
    }
}
exports.GetPostRequest = GetPostRequest;
/**
 * @generated from message blog.GetPostResponse
 */
class GetPostResponse extends protobuf_1.Message {
    /**
     * @generated from field: string id = 1;
     */
    id = "";
    /**
     * @generated from field: string author_id = 2;
     */
    authorId = "";
    /**
     * @generated from field: string title = 3;
     */
    title = "";
    /**
     * @generated from field: string content = 4;
     */
    content = "";
    /**
     * @generated from field: string image = 5;
     */
    image = "";
    /**
     * @generated from field: blog.Category category = 6;
     */
    category = Category.UNSPECIFIED;
    /**
     * @generated from field: int32 read_time = 7;
     */
    readTime = 0;
    /**
     * @generated from field: google.protobuf.Timestamp created_at = 8;
     */
    createdAt;
    /**
     * @generated from field: google.protobuf.Timestamp updated_at = 9;
     */
    updatedAt;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.GetPostResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "author_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 6, name: "category", kind: "enum", T: protobuf_1.proto3.getEnumType(Category) },
        { no: 7, name: "read_time", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
        { no: 8, name: "created_at", kind: "message", T: protobuf_1.Timestamp },
        { no: 9, name: "updated_at", kind: "message", T: protobuf_1.Timestamp },
    ]);
    static fromBinary(bytes, options) {
        return new GetPostResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GetPostResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GetPostResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(GetPostResponse, a, b);
    }
}
exports.GetPostResponse = GetPostResponse;
/**
 * @generated from message blog.ListPostsRequest
 */
class ListPostsRequest extends protobuf_1.Message {
    /**
     * @generated from field: int32 limit = 1;
     */
    limit = 0;
    /**
     * @generated from field: int32 offset = 2;
     */
    offset = 0;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.ListPostsRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "limit", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
        { no: 2, name: "offset", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    ]);
    static fromBinary(bytes, options) {
        return new ListPostsRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListPostsRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListPostsRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListPostsRequest, a, b);
    }
}
exports.ListPostsRequest = ListPostsRequest;
/**
 * @generated from message blog.ListPostsResponse
 */
class ListPostsResponse extends protobuf_1.Message {
    /**
     * @generated from field: repeated blog.GetPostResponse posts = 1;
     */
    posts = [];
    /**
     * @generated from field: int32 total_count = 2;
     */
    totalCount = 0;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.ListPostsResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "posts", kind: "message", T: GetPostResponse, repeated: true },
        { no: 2, name: "total_count", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    ]);
    static fromBinary(bytes, options) {
        return new ListPostsResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new ListPostsResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new ListPostsResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(ListPostsResponse, a, b);
    }
}
exports.ListPostsResponse = ListPostsResponse;
/**
 * @generated from message blog.DeletePostRequest
 */
class DeletePostRequest extends protobuf_1.Message {
    /**
     * @generated from field: string id = 1;
     */
    id = "";
    /**
     * @generated from field: string userId = 2;
     */
    userId = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.DeletePostRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "userId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new DeletePostRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DeletePostRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DeletePostRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DeletePostRequest, a, b);
    }
}
exports.DeletePostRequest = DeletePostRequest;
/**
 * @generated from message blog.DeletePostResponse
 */
class DeletePostResponse extends protobuf_1.Message {
    /**
     * @generated from field: string id = 1;
     */
    id = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.DeletePostResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new DeletePostResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new DeletePostResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new DeletePostResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(DeletePostResponse, a, b);
    }
}
exports.DeletePostResponse = DeletePostResponse;
/**
 * @generated from message blog.EditPostRequest
 */
class EditPostRequest extends protobuf_1.Message {
    /**
     * @generated from field: string id = 1;
     */
    id = "";
    /**
     * @generated from field: string userId = 2;
     */
    userId = "";
    /**
     * @generated from field: string title = 3;
     */
    title = "";
    /**
     * @generated from field: string content = 4;
     */
    content = "";
    /**
     * @generated from field: blog.Category category = 5;
     */
    category = Category.UNSPECIFIED;
    /**
     * @generated from field: string image = 6;
     */
    image = "";
    /**
     * @generated from field: int32 read_time = 7;
     */
    readTime = 0;
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.EditPostRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "userId", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "category", kind: "enum", T: protobuf_1.proto3.getEnumType(Category) },
        { no: 6, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 7, name: "read_time", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    ]);
    static fromBinary(bytes, options) {
        return new EditPostRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new EditPostRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new EditPostRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(EditPostRequest, a, b);
    }
}
exports.EditPostRequest = EditPostRequest;
/**
 * @generated from message blog.EditPostResponse
 */
class EditPostResponse extends protobuf_1.Message {
    /**
     * @generated from field: string id = 1;
     */
    id = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.EditPostResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new EditPostResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new EditPostResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new EditPostResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(EditPostResponse, a, b);
    }
}
exports.EditPostResponse = EditPostResponse;
/**
 * @generated from message blog.UploadUrlRequest
 */
class UploadUrlRequest extends protobuf_1.Message {
    /**
     * @generated from field: string filename = 1;
     */
    filename = "";
    /**
     * @generated from field: string content_type = 2;
     */
    contentType = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.UploadUrlRequest";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "filename", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "content_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new UploadUrlRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UploadUrlRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UploadUrlRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UploadUrlRequest, a, b);
    }
}
exports.UploadUrlRequest = UploadUrlRequest;
/**
 * @generated from message blog.UploadUrlResponse
 */
class UploadUrlResponse extends protobuf_1.Message {
    /**
     * @generated from field: string upload_url = 1;
     */
    uploadUrl = "";
    /**
     * @generated from field: string public_url = 2;
     */
    publicUrl = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "blog.UploadUrlResponse";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "upload_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "public_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new UploadUrlResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UploadUrlResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UploadUrlResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UploadUrlResponse, a, b);
    }
}
exports.UploadUrlResponse = UploadUrlResponse;
//# sourceMappingURL=blog_pb.js.map