"use strict";
// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts,import_extension=none"
// @generated from file blog/blog.proto (package blog, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostService = void 0;
const blog_pb_1 = require("./blog_pb");
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from service blog.PostService
 */
exports.PostService = {
    typeName: "blog.PostService",
    methods: {
        /**
         * @generated from rpc blog.PostService.CreatePost
         */
        createPost: {
            name: "CreatePost",
            I: blog_pb_1.CreatePostRequest,
            O: blog_pb_1.CreatePostResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc blog.PostService.GetPost
         */
        getPost: {
            name: "GetPost",
            I: blog_pb_1.GetPostRequest,
            O: blog_pb_1.GetPostResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc blog.PostService.ListPosts
         */
        listPosts: {
            name: "ListPosts",
            I: blog_pb_1.ListPostsRequest,
            O: blog_pb_1.ListPostsResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc blog.PostService.DeletePost
         */
        deletePost: {
            name: "DeletePost",
            I: blog_pb_1.DeletePostRequest,
            O: blog_pb_1.DeletePostResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc blog.PostService.EditPost
         */
        editPost: {
            name: "EditPost",
            I: blog_pb_1.EditPostRequest,
            O: blog_pb_1.EditPostResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
        /**
         * @generated from rpc blog.PostService.RequestUploadUrl
         */
        requestUploadUrl: {
            name: "RequestUploadUrl",
            I: blog_pb_1.UploadUrlRequest,
            O: blog_pb_1.UploadUrlResponse,
            kind: protobuf_1.MethodKind.Unary,
        },
    }
};
//# sourceMappingURL=blog_connect.js.map