"use strict";
// @generated by protoc-gen-es v1.10.1 with parameter "target=ts,import_extension=none"
// @generated from file common/types.proto (package common, syntax proto3)
/* eslint-disable */
// @ts-nocheck
Object.defineProperty(exports, "__esModule", { value: true });
exports.Empty = exports.UserInfo = void 0;
const protobuf_1 = require("@bufbuild/protobuf");
/**
 * @generated from message common.UserInfo
 */
class UserInfo extends protobuf_1.Message {
    /**
     * @generated from field: string id = 1;
     */
    id = "";
    /**
     * @generated from field: string email = 2;
     */
    email = "";
    /**
     * @generated from field: string display_name = 3;
     */
    displayName = "";
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "common.UserInfo";
    static fields = protobuf_1.proto3.util.newFieldList(() => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ]);
    static fromBinary(bytes, options) {
        return new UserInfo().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new UserInfo().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new UserInfo().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(UserInfo, a, b);
    }
}
exports.UserInfo = UserInfo;
/**
 * @generated from message common.Empty
 */
class Empty extends protobuf_1.Message {
    constructor(data) {
        super();
        protobuf_1.proto3.util.initPartial(data, this);
    }
    static runtime = protobuf_1.proto3;
    static typeName = "common.Empty";
    static fields = protobuf_1.proto3.util.newFieldList(() => []);
    static fromBinary(bytes, options) {
        return new Empty().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new Empty().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new Empty().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return protobuf_1.proto3.util.equals(Empty, a, b);
    }
}
exports.Empty = Empty;
//# sourceMappingURL=types_pb.js.map